project:
  type: website
  output-dir: docs

website:
  title: "br-visualization"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - minutes.qmd
      - aboutus.qmd
  site-url: "https://br-visualization.github.io/br-visualization/"
  repo-url: "https://github.com/BR-Visualization/br-visualization"
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

